### ISSUE TITLE
"Error: no offset found for function 'load_prc_file'.

### ISSUE THREAD

**Issue by RuiHirano** [ultimate-research/params-hook-plugin#5]
Hello.

I would like to create an API for Ryujinx + skyline to retrieve SSBU parameters.

I would like to use the params-hook-plugin, but I get the following error

```
Error: no offset found for function 'load_prc_file'. Refusing to install hook.
```

Here is the system version I am using.

Ryujinx: 1.1.209
NSP: SSBU v13.0.0
libparam_hook.nro: v13.0.1 (pre-release)

How can I solve this problem?
Thank you in advance.

**Comment by jugeeya** [comment]
It is likely because you were trying to use the `v13.0.1` of the param hook with SSBU 13.0.0. I'd suggest updating to 13.0.1, and we are currently working on getting a version that works with 13.0.2.
